Reaction/config/routes.rb
Rails.application.routes.draw do
  # resources :users
  root to: 'posts#index'

  get "/register", to: "users#new"

  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end

    resources :comments, only: [:create] do
      post 'vote'
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :create, :edit, :update]
end

Reaction/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reaction/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true

end

Reaction/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :votes, as: :voteable


  validates :body, presence: true;

  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

Reaction/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable


  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

Reaction/app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

Reaction/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 5}, on: :create
end

Reaction/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]

end

Reaction/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be loged in to do that"
      redirect_to root_path
    end
  end

end

Reaction/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] ="Category has been created"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

Reaction/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :require_user


  def create
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.user_id = current_user.id

    if @comment.save
      flash[:notice] = "Your comment was added"
      redirect_to post_path(@post)
    else
      render "posts/show"
    end
  end


  def vote
    comment = @post.comments.find_by(id: params[:comment_id])
    Vote.create(voteable: comment, user: current_user, vote: params[:vote])
    flash[:notice]  = "Your vote was counted"
    redirect_back(fallback_location: root_path)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end



end

Reaction/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{|post| post.total_votes}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Your post was created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit;

  end

  def update
    if @post.update(post_params)
      flash[:notice]  = "The post was updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    newVote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    if newVote.valid?
      flash[:notice]  = "Your vote was counted"
    else
      flash[:error] = "You can only vote once"
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:title,:url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  private

  def require_same_user
    if current_user != @post.user
      flash[:error] = "You are not allowed to do that"
      redirect_to root_path
    end
  end
end

Reaction/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && user.authenticate(params[:password])
      flash[:notice] = "Welcome, you've logged in."
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "There is something wrong with username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out"
    redirect_to root_path
  end

end

Reaction/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You are registered"
      redirect_to root_path
    else
      render :new
    end
  end

  def show

  end


  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "#{current_user.name} has been updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password)
    end

    def require_same_user
      binding.pry
      if current_user != @user
        flash[:error] = "You are not allowed to do that"
        redirect_to root_path
      end
    end
end

Reaction/app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?("http://")  ? str : "http://#{str}"
  end

  def display_time(dt)
    dt.strftime("%d/%m/%Y %l:%M%P")
  end
end

Reaction/app/helpers/posts_helper.rb
module PostsHelper
end

Reaction/app/helpers/users_helper.rb
module UsersHelper
end

Reaction/app/views/categories/_category.html.erb
 <span class="badge"><%= link_to category.name, category_path(category)%></span>

Reaction/app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category"%>

<%= render "shared/errors", obj: @category %>

<div class="well">
<%= form_for @category do |f|%>
  <div class="control-group">
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>

   <%= f.submit('Create Category',  class: 'btn btn-primary')%>
<%end%>

</div>

Reaction/app/views/categories/show.html.erb
<% header =  link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>


<%= render "shared/content_title", title: header%>

<% @category.posts.each do |post| %>
  <%= render "posts/post", post: post%>
<% end %>

Reaction/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

Reaction/app/views/layouts/_navigation.html.erb
<div class="nav">
  <div class="nav_item">
    <%= link_to "Not Reddit", root_path,  class: "btn btn-small"%>
  </div>

  <div class="btn-group nav_item">
    <%= link_to "#", class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do  %>
    Categories

    <% end %>
    <ul class="dropdown-menu">

    <% Category.all.each do |category| %>
      <li><%=link_to category.name, category_path(category)%></li>
    <% end %>

    <% if logged_in? %>
      <li class="divider"></li>

      <li>
        <%=link_to new_category_path do %>
          <i class="glyphicon glyphicon-plus"></i>
          New Category
        <% end %>
      <li>

    <% end %>
    </ul>

  </div>

  <% if logged_in? %>

    <div class="nav_item">
      <%= link_to "New Post", new_post_path, class: "btn btn-success btn-small"%>
    </div>

    <div class="btn-group">
      <%= link_to("", class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do  %>
        <%= current_user.name%>
      <% end %>
      <ul class="dropdown-menu">
        <li>
          <%=link_to edit_user_path(current_user) do %>
            <i class="glyphicon glyphicon-pencil"></i>
            Edit Profile
          <% end %>
        <li>
        <li>
          <%=link_to user_path(current_user) do %>
            <i class="glyphicon glyphicon-user"></i>
            View Profile
          <% end %>
        <li>
        <li>
          <%=link_to logout_path do %>
            <i class="glyphicon glyphicon-backward"></i>
            Logout
          <% end %>
        <li>
      </ul>
    </div>

    <div class="nav_item">
      <%= link_to "Logout", logout_path, class: "btn btn-small"%>
    </div>

  <% else #logged out path %>
    <div class="nav_item">
      <%= link_to "Register", register_path, class: "btn btn-success btn-small"%>
    </div>

    <div class="nav_item">
      <%= link_to "Log In", login_path, class: "btn btn-small"%>
    </div>
  <% end %>
</div>

Reaction/app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

Reaction/app/views/posts/_form.html.erb
<%= render "shared/errors", obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title%>
      <%= f.text_field :title%>
    </div>
    <div class="control-group">
      <%= f.label :url%>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description%>
      <%= f.text_area :description, rows: 3%>
    </div>

    <div class="control-group">
      <%= f.label "Categories"%>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <%cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post',  class: 'btn btn-primary')%>
  <% end %>
</div>

Reaction/app/views/posts/_post.html.erb
<div class="row">
  <div class="vote-box well text-center">
    <% if logged_in? %>
      <%=link_to vote_post_path(post, vote: true), method: "post" do%>
        <i class="glyphicon glyphicon-arrow-up"></i><br>
      <% end %>
    <% end %>
    <%= post.total_votes %> votes
    <br>
    <% if logged_in? %>
        <%=link_to vote_post_path(post, vote: false), method: "post" do%>
        <i class="glyphicon glyphicon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>

  <div class="big-box well">
    <%= render post.categories%>

  <h4><%= link_to post.title, fix_url(post.url)%></h4>
  <p><%=post.description%></p>
  <p>
    <span class="quiet">Posted by:</span> <%= link_to post.user.name, user_path(post.user) %>
    <small>at <%=display_time(post.created_at)%></small>
  </p>
  <small>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post))%>
    </span>
  </small>
  </div>
</div>

Reaction/app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit this post"%>

<%= render 'form'%>

Reaction/app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts"%>

<% @posts.each do |post| %>
  <%= render post %>
<% end %>

Reaction/app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new post"%>

<%= render 'form'%>

Reaction/app/views/posts/show.html.erb
<% if logged_in? %>
  <p class="pull-right">
    [<%= link_to "edit this post", edit_post_path(@post)%>]
  </p>
<% end %>

<%= render @post.categories%>

<%= render 'shared/content_title', title: @post.title%>

<p><%=@post.description%></p>
<hr>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment%>
    <div class="control-group">
      <%= f.label :body, "Leave a comment"%>
      <%= f.text_area :body, rows: 4%>
    </div>
    <%= f.submit('Create Comment',  class: 'btn btn-primary')%>
  <% end %>
<% end %>

<br>
  <h3>Comments</h3>
<br>

<div class="row">
  <% @post.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment%>
  <%end %>

</div>

Reaction/app/views/shared/_content_title.html.erb
<p class='lead'>
  <%=title%>
  <hr/>
</p>

Reaction/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>Please fix following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>