Ticketing/config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'projects#index'

  get "/register", to: "users#new"


  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'



  resources :projects
  resources :tickets do
    resources :comments, except: [:show, :new]
  end
  resources :tags, except: [:show]
end

Ticketing/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :ticket_tags, dependent: :destroy
  has_many :tickets, through: :ticket_tags

  validates :name, presence: true, length: {minimum: 3}
end

Ticketing/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]
  # before_action :require_same_user, except: [:index, :show]
  before_action :require_user, except: [:index, :show]



  def index
    @tags = Tag.all
  end

  def show

  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash[:notice] = "Your tag was created"
      redirect_to tags_path
    else
      flash.now[:error] = "Something went wrong"
      render :new
    end
  end

  def edit; end

  def update
    if @tag.update(tag_params)
      flash[:notice] = "Your tag was updated"
      redirect_to tags_path
    else
      flash.now[:error] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if @tag.destroy
      flash[:notice] = "Your tag was deleted"
      redirect_to tags_path
    else
      flash.now[:error] = "Tag unable to be deleted"
      render :show
    end
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

Ticketing/app/views/tags/_form.html.erb
<%= render "shared/errors", obj: @tag%>

<%= form_with(model: @tag, local: true) do |f| %>
  <div class="input-group">
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>
  <div class="input-group">
    <%= f.submit class: "btn btn-success"%>
    <%= link_to "Back", :back, class: "btn" %>
  </div>
<% end %>

Ticketing/app/views/tags/_list.html.erb
<tr>
  <td class="tg-01ax">
    <%= tag.name %><br>
  </td>
  <td class="tg-01ax"><%= link_to tag.tickets.size, tickets_path(tag_id: tag.id)  %></td>
  <td class="tg-01ax">
    <%= link_to "Edit tag", edit_tag_path(tag), class: "btn btn-success" %>
      <%= link_to "Delete", [tag], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>

  </td>
</tr>

Ticketing/app/views/tags/edit.html.erb
<%= render "shared/title", title: "Edit Tag"%>

<%= render "form", tag: @tag%>

Ticketing/app/views/tags/index.html.erb
<%= render "shared/title", title: "Tags"%>

<% if @tags.empty? %>
  <p class="empty-list">
    There are no tags!
    <%= link_to "Add one now?", new_tag_path %>
  </p>
<% else %>

<table class=tg>
  <thead>
    <tr>
      <th>Name</th>
      <th class="tg-cly1">Tickets</th>
      <th></th>
    </tr>
  </thead>
    <tbody>
    <% @tags.each do |tag| %>
      <%= render "list", tag: tag%>
    <% end %>
</tbody>
</table>
<%end %>

<%= link_to "New tag", new_tag_path, class: "btn btn-success"%>

Ticketing/app/views/tags/new.html.erb
<%= render "shared/title", title: "New Tag"%>

<%= render "form", tag: @tag%>