Ticketing/config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'projects#index'

  get "/register", to: "users#new"


  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'



  resources :projects
  resources :tickets do
    resources :comments, except: [:show, :new]
  end
  resources :tags, except: [:show]
end

Ticketing/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets, dependent: :destroy

  validates :name, presence: true, length: {minimum: 3}, uniqueness: true;
  validates :description, presence: true
end

Ticketing/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :show, :destroy]
  # before_action :require_same_user, except: [:index, :show]
  before_action :require_user, except: [:index, :show]


  def index
    @projects = Project.all
  end

  def show

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Your project was created"
      redirect_to projects_path
    else
      flash.now[:error] = "Something went wrong"
      render :new
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      flash[:notice] = "Your project was updated"
      redirect_to project_path(@project)
    else
      flash.now[:error] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:notice] = "Your project was deleted"
      redirect_to root_path
    else
      flash.now[:error] = "Record unable to be deleted"
      render :show
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

Ticketing/app/views/projects/_form.html.erb
<%= render "shared/errors", obj: @project%>

<%= form_for @project do |f| %>
  <div class="input-group">
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>
  <div class="input-group">
    <%= f.label :description%>
    <%= f.text_area :description%>
  </div>
  <div class="input-group">
    <%= f.submit class: "btn btn-success"%>
    <%= link_to "Back", :back, class: "btn" %>
  </div>
<% end %>

Ticketing/app/views/projects/_project.html.erb
<tr>
  <td class="tg-01ax">
    <strong><%= link_to project.name, project_path(project) %></strong><br>
    <%= project.description %>
  </td>
  <td class="tg-01ax"><%= project.tickets.open.count %></td>
  <td class="tg-01ax"><%= project.tickets.count %></td>
  <td class="tg-01ax">
    <%= link_to "Edit Project", edit_project_path(project), class: "btn btn-success" %>
    <%= link_to 'Delete', url_for(action: :destroy, controller: 'projects', id: project.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
  </td>
</tr>

Ticketing/app/views/projects/edit.html.erb
<%= render "shared/title", title: "Edit Project: #{@project.name}"%>

<%= render "form"%>

Ticketing/app/views/projects/index.html.erb
<%= render "shared/title", title: "Projects"%>

<% if @projects.empty? %>
  <p class="empty-list">
    There are no projects!
    <%= link_to "Add one now?", new_project_path %>
  </p>
<% else %>

  <table class=tg>
    <thead>
      <tr>
        <th>Name</th>
        <th class="tg-cly1">Open Tickets</th>
        <th class="tg-cly1">Total Tickets</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <%= render "project", project: project%>
      <% end %>
    </tbody>
  </table>

<% end %>
<br>

<%= link_to "New Project", new_project_path, class: "btn btn-success"%>

Ticketing/app/views/projects/new.html.erb
<%= render "shared/title", title: "New Project"%>

<%= render "form"%>

Ticketing/app/views/projects/show.html.erb
<%= render "shared/title", title: "#{@project.name} Project"%>

<table class=tg>
  <thead>
    <tr>
      <th>Name</th>
      <th class="tg-cly1">Open Tickets</th>
      <th class="tg-cly1">Total Tickets</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%=render "project",  project: @project %>
  </tbody>
</table>


<h2>Tickets</h2>

<% render "tickets/filter", tickets: @project.tickets%>

<%= render "tickets/list", tickets: @project.tickets%>